### ISSUE TITLE
Implement Programme Sheet Parser

### ISSUE THREAD

**Issue by firepenguindisopanda** [uwidcit/myAdvisorDev#78]
implement as a function that can be invoked locally via terminal
make the function accessible via a route (admin)  upload dept programmes

### The xlsx_parser.js file exists

- Investigate to determine if the function needs to refactor.
- To parse the file and store the data into the database
- create an admin route to allow a user to upload an excel sheet and parse that excel sheet.

### Assumptions

- We trust the admin routes are only accessed by an admin
- We trust the format of the excel file to be correct
- If a new file provided has less data than the previous, We'll keep the old data and just update the provided data (if it needs to updated)

**Comment by joshua-noel** [comment]
PR - https://github.com/uwidcit/myAdvisorDev/pull/90
