### ISSUE TITLE
Fix the foreign key and enum issues that occur when switched to postgresql database

### ISSUE THREAD

**Issue by firepenguindisopanda** [uwidcit/myAdvisorDev#85]
**As a** database administrator or software engineer
 **I need** to fix foreign key and enum issues that arise when switching to a PostgreSQL database
 **So that** the data can be stored without error

 ### Acceptance Criteria  
   
 ```gherkin
Given a database migration from another system (e.g., MySQL) to PostgreSQL
When the migration is performed
Then the foreign key constraints are correctly applied in PostgreSQL
And the enum types are correctly defined and utilized without causing application errors
 ```

**Comment by uni-paul-taylor2** [comment]
is the postgres db cleared from the start?

**Comment by firepenguindisopanda** [comment]
> is the postgres db cleared from the start?

When the application is started it is cleared depending on the .env variable

It's refreshed when using `npm run dev`

**Comment by firepenguindisopanda** [comment]
Fixed issue

[Git commit with fixes](https://github.com/uwidcit/myAdvisorDev/commit/63ef2405080add1454fa97638ede5aa196f0eddc)
